name: Publish Release
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'adopt'
            cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Get version
          id: version
          run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "target/CraftAMap*.jar"
            token: ${{ secrets.GITHUB_TOKEN }}
            name: "CraftAMap ${{ steps.version.outputs.version }}"
            tag: v${{ steps.version.outputs.version }}
